# Generated by Django 3.0.8 on 2020-07-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('confederation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='football.Confederation')),
            ],
        ),
    ]
